panel_configs = {
"#intercom1": {
	"Lights": [
		[ "light-1-spheres", "Table" ],
		[ "light-1-kitchen", "Kitchen" ],
		[ "stairs-1", "Stairs" ],
		[ "light-0-entry", "Entry" ],
		[ "light-1-dining", "Dining" ],
	],
	"Scenes": [
		[ "scene-1-breakfast", "Breakfast", "button" ],
		[ "scene-1-off", "Floor off", "button" ],
		[ "scene-1-dinner", "Dinner", "button" ],
		[ "scene-alloff", "All off", "button" ],
	],
	"Heat": [
		[ "radiator-1-bay", "Bay radiator", "radiator" ],
		[ "radiator-1-north", "Bench radiator", "radiator" ],
		[ "outlet-amps", "Amps", "outlet" ],
	],
	"#1 off": "zigbee/scene-1-off/set",
},
"#intercom2": {
	"Lights": [
		[ "light-2-office", "Office light", "colortemp" ],
		[ "light-2-craft", "Craft room light", "colortemp" ],
		[ "light-2-craftleds", "Printer light" ],
		[ "blinds-2-small", "Blinds", "blinds" ],
		[ "stairs-2", "Stairs up" ],
		[ "stairs-1", "Stairs down" ],
	],
	"Scenes": [
		[ "scene-2-bright", "Floor bright", "button" ],
		[ "scene-2-off", "Floor off", "button" ],
		[ "scene-alloff", "All off", "button" ],
	],
	"Heat": [
		[ "radiator-3-bay", "Office Radiator", "radiator" ],
		[ "radiator-2-office", "Office Radiator", "radiator" ],
		[ "outlet-amps", "Amps", "outlet" ],
	],
	"#2 off": "zigbee/scene-2-off/set",
},
"#intercom3": {
	"Lights": [
		[ "light-3-bedroom", "Main" ],
		[ "light-3-closet", "Closet" ],
		[ "light-3-bigegg", "Big Egg" ],
		[ "light-3-shower", "Shower" ],
		[ "stairs-3", "Stairs up" ],
		[ "light-3-bathroom", "Bathroom" ],
		[ "stairs-2", "Stairs down" ],
	],
	"Scenes": [
		[ "scene-3-bright", "Floor bright", "button" ],
		[ "scene-3-off", "Floor off", "button" ],
		[ "scene-alloff", "All off", "button" ],
	],
	"Heat": [
		[ "blinds-3-north", "Blinds Left", "blinds" ],
		[ "blinds-3-south", "Blinds Right", "blinds" ],
		[ "blinds-3-bay", "Blinds Bay", "blinds" ],
		[ "blinds-3-small", "Blinds South", "blinds" ],
		[ "radiator-3-bed", "Bed radiator", "radiator" ],
		[ "radiator-3-notbed", "Window radiator", "radiator" ],
		[ "radiator-3-bay", "Bay radiator", "radiator" ],
	],
	"#3 off": "zigbee/scene-3-off/set",
},
"#intercom4": {
	"Lights": [
		[ "light-4-sink", "Pantry" ],
		[ "light-4-north", "North" ],
		[ "light-4-desk", "Desk" ],
		[ "light-4-south", "South" ],
		[ "light-4-sphere", "Sphere" ],
		[ "stairs-4", "Stairs up" ],
		[ "light-4-smallegg", "Egg" ],
		[ "stairs-3", "Stairs down" ],
	],
	"Scenes": [
		[ "scene-intermission", "Intermission", "button" ],
		[ "scene-movie", "Movie time", "button" ],
		[ "scene-work", "Work lights", "button" ],
		[ "scene-alloff", "All off", "button" ],
		[ "/ir/projector", "Projector On", "button", "on" ],
		[ "/ir/projector", "Projector Off", "button", "off" ],
		[ "/denon/msg/send", "Source PS4", "button", "SIGAME" ],
		[ "/denon/msg/send", "Source VR PC", "button", "SIMPLAY" ],
	],
	"Heat": [
		[ "radiator-4-pantry", "Radiator", "radiator" ],
	],
	"#4 off": "zigbee/scene-4-off/set",
},
"#intercom0": {
	"Lights": [
		[ "light-0-entry", "Entry" ],
		[ "scene-alloff", "All off", "button" ],
		[ "stairs-1", "Stairs" ],
		[ "scene-allon", "All on", "button" ],
	],
	"All off": "zigbee/scene-alloff/set",
},
};
